[package]
name = "lex_lua"
version = "0.1.0"
authors = ["rfm <r@robertmasen.pizza>"]
edition = "2018"
descriptions = "A lexer for Lua"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2"
